--LOGIN TABLE
CREATE TABLE LOGIN(
LOGIN_ID NUMERIC(10,0),
PASSWORD VARCHAR(20) NOT NULL,
CONSTRAINT PK_LOGIN_ID_LOGIN PRIMARY KEY(LOGIN_ID)
);

--PROCEDURE TABLE
CREATE TABLE PROCEDURE_INFO(
PROCEDURE_ID NUMERIC(10,0),
PROCEDURE_DESCRIPTION VARCHAR(50) NOT NULL,
PROCEDURE_COST NUMERIC(10,2) NOT NULL,
DATE_CREATED DATETIME NOT NULL,
CREATED_BY NUMERIC(10,0) NOT NULL,
DATE_MODIFIED DATETIME,
MODIFIED_BY NUMERIC(10,0),
CONSTRAINT PK_PROCEDURE_ID_PROCEDURE PRIMARY KEY(PROCEDURE_ID),
CONSTRAINT UN_PROC_DESC_PROCEDURE UNIQUE(PROCEDURE_DESCRIPTION),
CONSTRAINT FK_CREATED_BY_PROCEDURE FOREIGN KEY(CREATED_BY) REFERENCES LOGIN(LOGIN_ID) 
);

--DOCTOR TABLE
CREATE TABLE DOCTOR(
DOCTOR_ID NUMERIC(10,0),
FIRSTNAME VARCHAR(20) NOT NULL,
LASTNAME VARCHAR(20) NOT NULL,
ADDRESS_LINE_1 VARCHAR(25) NOT NULL,
ADDRESS_LINE_2 VARCHAR(25),
CITY VARCHAR(20) NOT NULL,
PROVIENCE VARCHAR(2) NOT NULL,
POSTAL_CODE VARCHAR(7) NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
CONTACT_NO NUMERIC(10,0) NOT NULL,
DATE_CREATED DATETIME NOT NULL,
CREATED_BY NUMERIC(10,0) NOT NULL,
DATE_MODIFIED DATETIME,
MODIFIED_BY NUMERIC(10,0),
CONSTRAINT PK_DOCTOR_ID_DOCTOR PRIMARY KEY(DOCTOR_ID),
CONSTRAINT FK_CREATED_BY_DOCTOR FOREIGN KEY(CREATED_BY) REFERENCES LOGIN(LOGIN_ID) 
);

--PATIENT TABLE
CREATE TABLE PATIENT(
PATIENT_ID NUMERIC(10,0),
FIRSTNAME VARCHAR(20) NOT NULL,
LASTNAME VARCHAR(20) NOT NULL,
ADDRESS_LINE_1 VARCHAR(25) NOT NULL,
ADDRESS_LINE_2 VARCHAR(25),
CITY VARCHAR(20) NOT NULL,
PROVIENCE VARCHAR(2) NOT NULL,
POSTAL_CODE VARCHAR(7) NOT NULL,
DOB DATETIME NOT NULL,
EMAIL VARCHAR(25) NOT NULL,
CONTACT_NO NUMERIC(10,0) NOT NULL,
DATE_CREATED DATETIME NOT NULL,
CREATED_BY NUMERIC(10,0) NOT NULL,
DATE_MODIFIED DATETIME,
MODIFIED_BY NUMERIC(10,0),
CONSTRAINT PK_PATIENT_ID_PATIENT PRIMARY KEY(PATIENT_ID),
CONSTRAINT FK_CREATED_BY_PATIENT FOREIGN KEY(CREATED_BY) REFERENCES LOGIN(LOGIN_ID),
CONSTRAINT CK_PROVIENCE_PATIENT CHECK(PROVIENCE IN('ON','QC','NS','NB','MB','BC','PE','SK','AB','NL'))
);

--APPOINTMENT TABLE
CREATE TABLE APPOINTMENT(
APPOINTMENT_ID NUMERIC(10,0),
PATIENT_ID NUMERIC(10,0) NOT NULL,
DOCTOR_ID NUMERIC(10,0) NOT NULL,
APPOINTMENT_DATE DATETIME NOT NULL,
APPOINTMENT_TIME VARCHAR(10) NOT NULL,
DATE_CREATED DATETIME NOT NULL,
CREATED_BY NUMERIC(10,0) NOT NULL,
DATE_MODIFIED DATETIME,
MODIFIED_BY NUMERIC(10,0),
CONSTRAINT PK_APPT_ID_APPOINTMENT PRIMARY KEY(APPOINTMENT_ID),
CONSTRAINT FK_PATIENT_ID_APPOINTMENT FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
CONSTRAINT FK_DOCTOR_ID_APPOINTMENT FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
CONSTRAINT FK_CREATED_BY_APPOINTMENT FOREIGN KEY(CREATED_BY) REFERENCES LOGIN(LOGIN_ID)
);

--PATIENT HISTORY TABLE
CREATE TABLE PATIENT_HISTORY(
PATIENT_HISTORY_ID NUMERIC(10,0),
PATIENT_ID NUMERIC(10,0) NOT NULL,
APPOINTMENT_ID NUMERIC(10,0),
DOCTOR_ID NUMERIC(10,0) NOT NULL,
PROCEDURE_ID NUMERIC(10,0) NOT NULL,
DATE_CREATED DATETIME NOT NULL,
CREATED_BY NUMERIC(10,0) NOT NULL,
DATE_MODIFIED DATETIME,
MODIFIED_BY NUMERIC(10,0),
CONSTRAINT PK_PH_ID_PATIENT_HISTORY PRIMARY KEY(PATIENT_HISTORY_ID),
CONSTRAINT FK_PAT_ID_PATIENT_HISTORY FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
CONSTRAINT FK_APPT_ID_PATIENT_HISTORY FOREIGN KEY(APPOINTMENT_ID) REFERENCES APPOINTMENT(APPOINTMENT_ID),
CONSTRAINT FK_DOC_ID_PATIENT_HISTORY FOREIGN KEY(DOCTOR_ID) REFERENCES DOCTOR(DOCTOR_ID),
CONSTRAINT FK_PROC_ID_PATIENT_HISTORY FOREIGN KEY(PROCEDURE_ID) REFERENCES PROCEDURE_INFO(PROCEDURE_ID),
CONSTRAINT FK_CREATED_BY_PATIENT_HISTORY FOREIGN KEY(CREATED_BY) REFERENCES LOGIN(LOGIN_ID)
);